admin_menu_item_index:
    path:     /
    defaults: { _controller: "YaCMSBundle:MenuItem:index" }
    methods:  GET

admin_menu_item_show:
    path:     /{id}/show
    defaults: { _controller: "YaCMSBundle:MenuItem:show" }
    methods:  GET

admin_menu_item_new:
    path:     /new
    defaults: { _controller: "YaCMSBundle:MenuItem:new" }
    methods:  [GET, POST]

admin_menu_item_edit:
    path:     /{id}/edit
    defaults: { _controller: "YaCMSBundle:MenuItem:edit" }
    methods:  [GET, POST]

admin_menu_item_delete:
    path:     /{id}/delete
    defaults: { _controller: "YaCMSBundle:MenuItem:delete" }
    methods:  DELETE
