<?php

namespace YaCMSBundle\Repository;

/**
 * InterfaceLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterfaceLabelRepository extends \Doctrine\ORM\EntityRepository
{
}
