YaCMSBundle\Entity\Locale:
    type: entity
    table: null
    repositoryClass: YaCMSBundle\Repository\LocaleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            nullable: false
    fields:
        name:
            type: string
            length: 8
            unique: true
            nullable: false
        country:
            type: string
            length: 64
            nullable: false
        lang:
            type: string
            length: 64
            nullable: false

    indexes:
        search_idx:
            columns:
              - lang
              - name

    oneToMany:
        menus:
            targetEntity: YaCMSBundle\Entity\Menu
            mappedBy: locale
        menuItems:
            targetEntity: YaCMSBundle\Entity\MenuItem
            mappedBy: locale
        assets:
            targetEntity: YaCMSBundle\Entity\Asset
            mappedBy: locale
        articles:
            targetEntity: YaCMSBundle\Entity\Article
            mappedBy: locale
        tags:
            targetEntity: YaCMSBundle\Entity\Tag
            mappedBy: locale
    lifecycleCallbacks: {  }
